"""Merge the seven ADIT atlas fragments into one atlas: jev-atlas/atlas/adit.json.

    python3 jev-atlas/tools/merge.py    # writes atlas/adit.json, loads it with the harness's atlas.py,
                                        # prints a summary and the file's sha256

The fragments in atlas/parts/ are generated by tools/<area>/build.py (gen.py for
programmes); regenerate a fragment there, then rerun this script. Nothing here is
hand-edited JSON: every change the merge makes to a fragment is a rule below.

What the merge does (see atlas/README.md):
- one atlas-level `selectors`;
- the URL pages in an explicit order (specific routes before general ones; the
  not-found page last, as a catch-all), overlays after them;
- the five chrome facts (signed-in user, people and roles, highlighted section, unread and awaiting
  counts, toast) once, as the atlas-level `global_facts_js`, and the fragments' own
  copies of the signed-in and toast facts dropped;
- cross-area `leads_to` values rewritten as page ids;
- one copy of each shared component (sort headings, pager, toast Dismiss and Open,
  dialog close cross and Cancel, comments box and Post comment, chart disclosure,
  provenance stamp, footer and account-menu User Manual links, and a fallback for
  breadcrumbs);
- top bar, breadcrumb, footer and account menu told apart by `landmark`;
- the second-round rules in harness2.py (catch-all record links replaced by route
  keys, entries broken by the new row labels rekeyed, row buttons keyed by their row,
  virtual controls the reader now offers natively replaced by entries);
- control order: dialog-overlay entries first (they share text with the page
  buttons that open them), then the global chrome fragment in its own order (the
  account left column before the account menu and tray), then the areas, then the
  shared components.
"""
import copy
import hashlib
import importlib.util
import json
import os
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
import harness2 as H2  # noqa: E402

HERE = pathlib.Path(__file__).resolve().parent
SHIM = HERE.parent
PARTS = SHIM / "atlas" / "parts"
OUT = SHIM / "atlas" / "adit.json"
HARNESS = os.environ.get("JEV_CLONE", str(__import__('pathlib').Path(__file__).resolve().parents[1] / 'vendor' / 'jev-ultrafast')).rstrip("/")
AREAS = ["portfolio-global", "projects", "programmes", "drilling-assays", "resources-optimiser", "approvals", "admin"]
VERSION = "2026-09-22-merged-h4"

parts = {a: json.loads((PARTS / f"{a}.json").read_text()) for a in AREAS}

# ---------------------------------------------------------------- pages
pages, page_area = {}, {}
for area in AREAS:
    for p in parts[area]["pages"]:
        if p["id"] in pages:
            sys.exit(f"duplicate page id {p['id']} ({page_area[p['id']]} and {area})")
        pages[p["id"]] = copy.deepcopy(p)
        page_area[p["id"]] = area

URL_ORDER = [
    # portfolio-global
    "portfolio-commodity", "portfolio-jurisdiction", "portfolio-analytics", "portfolio-budget", "portfolio",
    "search", "notifications",
    "account-notifications", "account-preferences", "account-security", "account-profile", "manual",
    # projects
    "projects-new", "project-tenure", "project-programmes", "project-drilling", "project-assays",
    "project-resource", "project-budget", "project-approvals", "project-activity", "project-overview",
    "projects-register",
    # programmes
    "programmes-new", "programmes-schedule", "programmes-rigs", "programmes-camps", "programmes-crew-rotations",
    "programme-crew", "programme-logistics", "programme-holes", "programme-approval", "programme-overview",
    "programmes-list",
    # drilling-assays
    "drilling-intercepts", "drilling-hole", "drilling-list",
    "assays-new", "assays-qaqc", "assays-samples", "assays-batch", "assays-batches",
    # resources-optimiser
    "resources-estimate-new", "resources-estimate", "resources-estimates", "resources-forecast",
    "resources-price-deck", "resources-valuation", "resources-portfolio",
    "optimiser-scenarios", "optimiser-targets", "optimiser",
    # approvals
    "approval-detail", "approvals-queue",
    # admin
    "admin-price-deck", "admin-qaqc", "admin-workflows", "admin-reference", "admin-users", "admin-roles",
    "admin-audit", "admin-settings",
    # catch-all, last
    "not-found",
]
url_ids = [i for i, p in pages.items() if p.get("layer") != "overlay"]
overlay_ids = [i for i, p in pages.items() if p.get("layer") == "overlay"]
assert sorted(URL_ORDER) == sorted(url_ids), set(URL_ORDER) ^ set(url_ids)
CHROME_OVERLAYS = {"notification-tray", "account-menu"}
DIALOG_OVERLAYS = [i for i in overlay_ids if i not in CHROME_OVERLAYS]

# Route fixes found while merging (observed live 2026-09-22).
# #/admin/system renders System settings, like #/admin.
pages["admin-settings"]["match"] = {"url_regex": "#/admin(/system)?/?(\\?.*)?$"}
# #/portfolio/<anything else> renders the stage board (route portfolio/:shape); the four
# named shapes are matched first, so this only catches the rest.
pages["portfolio"]["match"] = {"url_regex": "#/portfolio(/[^/?#]*)?/?(\\?.*)?$"}
# The app's not-found page is shown for any unknown top-level route and for unknown
# sub-routes of the sections whose children are fixed (#/admin/x, #/resources/x ...).
# It is last in the file, after every real page.
ROOTS = "portfolio|projects|programmes|drilling|assays|resources|approvals|optimiser|admin|search|notifications|account|manual"
pages["not-found"]["match"] = {
    "url_regex": f"#/(?!$)(?!({ROOTS})(/|\\?|$))|#/(admin|resources|account|optimiser|search|notifications)/"
}
pages["not-found"]["not_here"] = (
    "This page answers unknown addresses, at the top level and under Administration, Resources, "
    "Optimiser, My account, Search and Notifications. An unknown record id shows its own not-found "
    "message inside its section. The application's sections: the top navigation."
)

# Overlay selectors that caught another area's dialog, or missed a route (observed live).
# The batch Reject dialog ("Reject LAB-...") also matched the approval Reject overlay.
pages["approval-reject-dialog"]["match"] = {"selector": 'dialog.dlg[open][aria-label^="Reject WF-"]'}
# #/admin/system does not mark the #/admin section link current; the aria-label alone is unique.
pages["admin-reset-tenant-dialog"]["match"] = {"selector": 'dialog.dlg[open][aria-label="Reset the demonstration tenant"]'}

# ---- facts: the five chrome facts on every URL page, once.
chrome_page = parts["portfolio-global"]["pages"][0]
CHROME_FACTS = chrome_page["facts_js"][:5]
assert "Signed in as" in CHROME_FACTS[0] and "People and roles" in CHROME_FACTS[1]
assert "Top-bar section" in CHROME_FACTS[2] and "unread" in CHROME_FACTS[3] and ".toast" in CHROME_FACTS[4]


def duplicate_fact(expr):
    """A fragment's own copy of a chrome fact: the signed-in user or the toast message."""
    if expr in CHROME_FACTS:
        return True
    if "toast" in expr and "dialog" not in expr:
        return True
    if "Signed in as" in expr and "currentUserId" in expr:
        return True
    return False


dropped_facts = 0
for pid in url_ids:
    p = pages[pid]
    own = [e for e in p.get("facts_js", []) if not duplicate_fact(e)]
    dropped_facts += len(p.get("facts_js", [])) - len(own)
    p["facts_js"] = own  # the chrome facts are read once, as global_facts_js

# ---- leads_to: page ids only.
LEADS = {
    ("portfolio", "Stage column head"): "projects-register",
    ("portfolio", "Project ticket or project id"): "project-overview",
    ("portfolio", "Needs attention item"): ["approval-detail", "project-tenure", "assays-batch", "programme-overview", "project-overview"],
    ("portfolio", "Projects register / Full register"): "projects-register",
    ("portfolio", "Approvals button"): "approvals-queue",
    ("portfolio-commodity", "Project id / name link"): "project-overview",
    ("portfolio-commodity", "Shape links (left column)"): ["portfolio", "portfolio-jurisdiction", "portfolio-analytics", "portfolio-budget"],
    ("portfolio-jurisdiction", "Project id / name link"): "project-overview",
    ("portfolio-jurisdiction", "Shape links (left column)"): ["portfolio", "portfolio-commodity", "portfolio-analytics", "portfolio-budget"],
    ("portfolio-analytics", "Project names in chart value tables"): "project-overview",
    ("portfolio-analytics", "Shape links (left column)"): ["portfolio", "portfolio-commodity", "portfolio-jurisdiction", "portfolio-budget"],
    ("portfolio-budget", "Variance requests"): "approvals-queue",
    ("portfolio-budget", "Project id link"): "project-overview",
    ("portfolio-budget", "Shape links (left column)"): ["portfolio", "portfolio-commodity", "portfolio-jurisdiction", "portfolio-analytics"],
    ("search", "Result link"): ["project-overview", "programme-overview", "drilling-hole", "assays-batch", "approval-detail", "resources-estimate", "project-tenure"],
    ("notifications", "Notification title"): ["approval-detail", "project-overview", "project-tenure", "programme-overview", "drilling-hole", "assays-batch", "resources-estimate"],
    ("notifications", "Settings"): "account-notifications",
    ("manual", "Contents entries"): "manual",
    **{(p, "Project name under the title"): "project-overview" for p in (
        "programme-overview", "programme-crew", "programme-logistics", "programme-holes", "programme-approval")},
    ("programme-overview", "Approval link"): "approval-detail",
    ("programme-approval", "Approval request id"): "approval-detail",
    ("programme-holes", "Hole id in a row"): "drilling-hole",
    ("programmes-list", "Project name in a row"): "project-overview",
    ("programmes-camps", "Project name in a row"): "project-overview",
    ("drilling-intercepts", "Project link"): "project-overview",
    ("drilling-hole", "Project link under the heading"): "project-overview",
    ("drilling-hole", "Programme link under the heading"): "programme-overview",
    ("drilling-list", "Project link"): "project-overview",
    ("drilling-list", "Programme code link"): "programme-overview",
    ("assays-new", "Submit dispatch"): "assays-new",
    ("assays-qaqc", "Tolerances"): "admin-qaqc",
    ("assays-qaqc", "Laboratory link"): "assays-batches",
    ("assays-qaqc", "Project link in By project"): "project-assays",
    ("assays-qaqc", "Bar in Failures by project"): "assays-batches",
    ("assays-batch", "Project link"): "project-overview",
    ("assays-batches", "Project link"): "project-overview",
    ("resources-estimate", "Release request button"): "approval-detail",
    ("resources-estimates", "Project link"): "project-overview",
    ("resources-portfolio", "Project link"): "project-resource",
    ("optimiser-targets", "Project link"): "project-overview",
    ("optimiser", "Project link"): "project-overview",
    ("approval-detail", "Subject link (Request panel)"): ["programme-overview", "project-overview", "resources-estimate", "project-tenure", "programmes-list"],
    ("approval-detail", "Project link (head)"): "project-overview",
    ("approvals-queue", "Queue and By type links (left column)"): "approvals-queue",
    ("admin-price-deck", "View in Resources"): "resources-price-deck",
    ("admin-qaqc", "Assays (top navigation)"): "assays-batches",
}
unresolved = []
for pid, p in pages.items():
    lt = p.get("leads_to")
    if not lt:
        continue
    for label, target in list(lt.items()):
        if (pid, label) in LEADS:
            lt[label] = LEADS[(pid, label)]
            continue
        if isinstance(target, str):
            pieces = [t.strip() for t in re.split(r"\s*/\s*|,\s*", target) if t.strip()]
            if all(t in pages for t in pieces):
                lt[label] = pieces[0] if len(pieces) == 1 else pieces
                continue
        unresolved.append(f"{pid} / {label!r}: {target!r}")
if unresolved:
    sys.exit("leads_to not resolved to page ids:\n  " + "\n  ".join(unresolved))
for pid, p in pages.items():
    for label, target in (p.get("leads_to") or {}).items():
        for t in [target] if isinstance(target, str) else target:
            assert t in pages, (pid, label, t)

# ---------------------------------------------------------------- controls

SHARED = {
    "sort": {"key": {"text_regex": "^Sort by ", "role": "button"},
             "region": "Table column heading",
             "what": "Sorts the table by the column named in its label; pressing it again reverses the order. Only the order of the rows changes.",
             "not_for": "Filtering which rows are shown (the filters above a table and the left column do that). Sorting applies to the columns whose heading carries this button."},
    "pager": {"key": {"role": "button", "text_regex": "^(First|Previous|Next|Last)$"},
              "region": "Pager under a table",
              "what": "Moves the table above to its first, previous, next or last page of rows; the table footer says which rows are showing. Appears only when a table has more rows than fit on one page.",
              "not_for": "Changing the filters or the sort, or moving between records or tabs."},
    "dismiss": {"key": {"text": "Dismiss", "role": "button"},
                "region": "Message toast (bottom of screen)",
                "what": "Closes the short message that confirmed or reported the last action.",
                "not_for": "Undoing the action the message reports; the action stays done."},
    "toast-open": {"key": {"role": "link", "text_regex": "^Open(\\s+\\S.*)?$"},
                   "region": "Confirmation message (the toast at the bottom of the screen, or the notice a form page shows after it is submitted)",
                   "what": "Opens the record the confirmation is about (the batch, estimate or request just created).",
                   "not_for": "Dismissing the message (Dismiss) or undoing the action."},
    "close": {"key": {"text": "Close dialog", "role": "button"},
              "region": "Open dialog, title bar (the cross at the top right)",
              "what": "Closes the open dialog without saving, submitting or deciding anything, the same as its Cancel button where it has one.",
              "not_for": "Confirming the dialog; that is its primary button (Save, Submit, Approve and so on)."},
    "cancel": {"key": {"text": "Cancel", "role": "button"},
               "region": "Open dialog, buttons at the bottom",
               "what": "Closes the open dialog without saving, submitting or deciding anything; the record is unchanged.",
               "not_for": "Cancelling, withdrawing or deleting the record itself (Cancel only abandons the dialog), or confirming (the dialog's primary button beside it)."},
    "comment": {"key": {"role": "textbox", "text_regex": "^(Open )?Add a comment$"},
                "region": "Comments panel of a record page",
                "what": "Text of a new comment on the record this page shows (a project, programme, hole, batch, estimate or approval request). Typing @ and a colleague's first name mentions them, so they are notified when it is posted. The comment is kept once it is posted (Post comment).",
                "not_for": "Changing the record's own fields, or the note or reason of a decision (those are in the record's dialogs)."},
    "post": {"key": {"text": "Post comment", "role": "button"},
             "region": "Comments panel of a record page",
             "what": "Posts the text typed in the comment box to this record's comments, under the signed-in user's name, and clears the box. Offered only while the box has text.",
             "not_for": "Saving, approving or otherwise changing the record itself."},
    "values": {"key": {"text": "Values behind this chart", "role": "button"},
               "region": "Chart disclosure, under a chart",
               "what": "Opens or closes a table under the chart holding the exact figures the chart is drawn from.",
               "not_for": "Changing the chart, filtering the page or exporting data; it only reveals values in place."},
    "provenance": {"key": {"role": "button", "text_regex": "^(read from|computed by) "},
                   "region": "Provenance stamp, under a row of summary figures",
                   "what": "Says which records the figures around it were read or computed from. Where it offers show method, pressing it shows or hides how the figures are computed (and, on an estimate, its author, reviewer and notes); otherwise it is a label.",
                   "not_for": "Changing, refreshing or recalculating any figure, or opening the records it counts."},
    "manual-link": {"key": {"text": "User Manual", "role": "link", "landmark": "contentinfo"},
                    "region": "Page footer",
                    "what": "Opens the ADIT User Manual, at its contents page.",
                    "not_for": "Help about the current record; the manual describes pages in general."},
    "manual-menu": {"key": {"text": "User Manual", "role": "link", "page": "account-menu", "landmark": "banner"},
                    "region": "Account menu (top bar drop-down)",
                    "what": "Opens the ADIT User Manual, at its contents page.",
                    "not_for": "Help about the current record; the manual describes pages in general. Switching user (the list below)."},
    "breadcrumb": H2.BREADCRUMB_SHARED,
}


def shared_kind(key, area):
    """Which shared component a fragment entry duplicates, or None to keep it."""
    t, tr, rl, page = key.get("text"), key.get("text_regex", ""), key.get("row_label"), key.get("page")
    if tr == "^Sort by ":
        return "sort"
    if tr == "^(First|Previous|Next|Last)$" or (t in ("First", "Previous", "Next", "Last") and key.get("role") == "button"):
        return "pager"
    if t == "Dismiss":
        return "dismiss"
    if t == "Close dialog":
        return "close"
    if (t == "Cancel" or tr == "^Cancel$") and page in DIALOG_OVERLAYS:
        return "cancel"
    if rl == "Add a comment" or tr.startswith("^(Open )?Add a comment"):
        return "comment"
    if t == "Post comment":
        return "post"
    if t == "Values behind this chart":
        return "values"
    if re.match(r"\^(\(read from\|computed by\)|read from|computed by)", tr):
        return "provenance"
    if t == "User Manual" and key.get("role") == "link":
        return "manual-link"
    return None


# Chrome and account-menu/tray labels no catch-all record link may capture.
CHROME_LABELS = ["ADIT home", "Skip to content", "Portfolio", "Projects", "Programmes", "Drilling", "Assays",
                 "Resources", "Optimiser", "Admin", "Approvals", "User Manual", "Open", "My profile",
                 "Preferences", "Notification settings", "All notifications", "Mark all read"]
GUARD = "(?!(?:" + "|".join(re.escape(x) for x in CHROME_LABELS) + ")$)(?!Approvals\\s*\\()(?!User Manual)(?!Open\\s)"
guarded = 0


def guard_catch_all(key):
    """Prefix a catch-all record-link regex with the chrome guard."""
    global guarded
    tr = key.get("text_regex")
    if key.get("role") == "link" and tr and tr.startswith("^(?!") and key.get("page"):
        key["text_regex"] = "^" + GUARD + tr[1:]
        guarded += 1


dialog_first, chrome, areas_rest, removed = [], [], [], {}
for area in AREAS:
    for c in parts[area]["controls"]:
        c = copy.deepcopy(c)
        kind = shared_kind(c["key"], area)
        if kind:
            removed.setdefault(kind, []).append(area)
            continue
        guard_catch_all(c["key"])
        c["area"] = area
        if area == "portfolio-global":
            chrome.append(c)
        elif c["key"].get("page") in DIALOG_OVERLAYS:
            dialog_first.append(c)
        else:
            areas_rest.append(c)

# A button in a form row borrows the row's label, so a field keyed {page, row_label}
# alone also took the dialog's Save and Cancel (observed live): key those fields by role too.
ROLE_FIX = {("optimiser-dlg-save-scenario", "Name"): "textbox",
            ("reject-batch-dialog", "Reason sent to the laboratory"): "textbox"}
for c in dialog_first + areas_rest:
    k = c["key"]
    if set(k) == {"page", "row_label"} and (k["page"], k["row_label"]) in ROLE_FIX:
        k["role"] = ROLE_FIX[(k["page"], k["row_label"])]

shared = []
for kind, entry in SHARED.items():
    e = copy.deepcopy(entry)
    e["area"] = "shared"
    shared.append(e)

controls = dialog_first + chrome + areas_rest + shared

# Second round: the upgraded harness (href routes, row identities, landmarks, native date
# inputs and hidden toggles). See harness2.py.
for pid, p in pages.items():
    p["area"] = page_area[pid]
controls, upgrade_report = H2.upgrade(controls, pages, DIALOG_OVERLAYS, GUARD)
for c in controls:
    if c["key"].get("text_regex", "").startswith("^" + GUARD):
        sys.exit(f"catch-all left after the upgrade: {c['area']} {c['key'].get('page')}")

# Sanity: every key field known, every page reference exists, no exact duplicate keys.
spec = importlib.util.spec_from_file_location("harness_atlas", f"{HARNESS}/jev_ultrafast/atlas.py")
A = importlib.util.module_from_spec(spec)
spec.loader.exec_module(A)
seen_keys = {}
for c in controls:
    for f in c["key"]:
        assert f in A.KEY_FIELDS, f
    if "page" in c["key"]:
        assert c["key"]["page"] in pages, c["key"]
    for f in ("text_regex", "id_regex", "href_regex"):
        if f in c["key"]:
            re.compile(c["key"][f])
    sig = json.dumps(c["key"], sort_keys=True)
    if sig in seen_keys:
        sys.exit(f"duplicate key {sig} ({seen_keys[sig]} and {c['area']})")
    seen_keys[sig] = c["area"]

# The guard really keeps chrome labels out of every catch-all.
chrome_samples = CHROME_LABELS + ["Approvals ( 3  awaiting you)", "User Manual (opens in a new tab)"]
for c in controls:
    tr = c["key"].get("text_regex")
    if c["key"].get("role") == "link" and tr and tr.startswith("^" + GUARD) and c["key"]["page"] not in CHROME_OVERLAYS:
        for label in chrome_samples:
            if re.search(tr, label) and c["key"].get("text") is None and "row_label" not in c["key"]:
                sys.exit(f"catch-all {c['key']} captures chrome label {label!r}")

for p in pages.values():
    p["area"] = page_area[p["id"]]

ordered_pages = [pages[i] for i in URL_ORDER] + [pages[i] for i in overlay_ids if i in CHROME_OVERLAYS] + \
                [pages[i] for i in DIALOG_OVERLAYS]

atlas = {
    "app": "ADIT",
    "version": VERSION,
    "selectors": {"dialog": ["dialog[open]"]},
    "global_facts_js": CHROME_FACTS,
    "pages": ordered_pages,
    "controls": controls,
}
# The learned layer (tools/learn.py): accepted lessons from failed runs, applied last and
# counted in the version, so the generated atlas above is unchanged underneath them.
import learn  # noqa: E402
lessons = learn.accepted_lessons()
if lessons:
    atlas = learn.apply(atlas, lessons)
    atlas["version"] = f"{VERSION}+learned-{len(lessons)}"
raw = (json.dumps(atlas, indent=1, ensure_ascii=False) + "\n").encode()
OUT.write_bytes(raw)

book = A.load(OUT)
print(f"wrote {OUT.relative_to(SHIM.parent)}: {len(ordered_pages)} pages ({len(url_ids)} URL, {len(overlay_ids)} overlays), "
      f"{len(controls)} controls (dialog {len(dialog_first)}, chrome {len(chrome)}, areas {len(areas_rest)}, shared {len(shared)})")
print("removed as shared:", {k: len(v) for k, v in removed.items()})
print(f"catch-alls guarded: {guarded}; chrome/toast facts dropped from fragments: {dropped_facts}; "
      f"chrome facts now global: {len(CHROME_FACTS)}")
for k, v in upgrade_report.items():
    print(f"harness2: {k}: {v}")
print(f"learned lessons applied: {len(lessons)}; version {atlas['version']}")
print("sha256", hashlib.sha256(raw).hexdigest(), "| harness digest", book.sha256, "| load OK")
